name: Production CD

on:
  push:
    branches:
      - production

jobs:
  deploy-frontpage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Write Git SHA
        run: echo ${{ github.sha }} > frontpage/git.sha
      # unconditionally deploy everything (~100MB / deploy)
      # TODO: Since we only deploy from git without changes, we could grab the
      # git hash we deployed, diff to that, and then deploy the differing files only
      - name: S3 Sync
        run: aws s3 sync frontpage/ s3://www.losaltoshacks.com/
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
      - name: Cloudfront Invalidation
        run: aws cloudfront create-invalidation --distribution-id EBQXN8COJP8X4 --paths '/*'
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
  deploy-ffmergebot:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set AWS Region
        run: aws configure set default.region us-west-2
      - name: Login to AWS ECR
        run: eval $(aws ecr get-login --no-include-email)
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
      - name: Pull Cache from ECR
        run: docker pull 380692441471.dkr.ecr.us-west-2.amazonaws.com/ffmergebot:latest
      - name: Build Container
        run: >-
          docker build
          --pull
          --build-arg environment=prod
          --tag 380692441471.dkr.ecr.us-west-2.amazonaws.com/ffmergebot
          --cache-from 380692441471.dkr.ecr.us-west-2.amazonaws.com/ffmergebot:latest
          mergebot
      - name: Push to ECR
        run: docker push 380692441471.dkr.ecr.us-west-2.amazonaws.com/ffmergebot
      - name: Force ECR Redeploy
        run: aws ecs update-service --cluster LosAltosHacksCluster --service FFMergeBotService --force-new-deployment > /dev/null
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
  deploy-reg-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set AWS Region
        run: aws configure set default.region us-west-2
      - name: Login to AWS ECR
        run: eval $(aws ecr get-login --no-include-email)
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
      - name: Pull Cache from ECR
        run: docker pull 380692441471.dkr.ecr.us-west-2.amazonaws.com/registration-backend:latest
      - name: Build Container
        run: >-
          docker build
          --pull
          --tag 380692441471.dkr.ecr.us-west-2.amazonaws.com/registration-backend
          --cache-from 380692441471.dkr.ecr.us-west-2.amazonaws.com/registration-backend:latest
          registration/backend
      - name: Push to ECR
        run: docker push 380692441471.dkr.ecr.us-west-2.amazonaws.com/registration-backend
      - name: Force ECR Redeploy
        run: aws ecs update-service --cluster LosAltosHacksCluster --service RegistrationBackendService --force-new-deployment > /dev/null
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

          

